- name: Add user configuration files
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .bash_aliases.d
    - .bash_completions.d
    - .bash_env.d
    - .gitignore_global
    - .nanorc
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Add user configuration templates
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: home/{{ item }}.j2
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .gitconfig

- name: Install oh-my-zsh
  become: yes
  become_user: '{{ user_name }}'
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    version: master
    dest: '/home/{{ user_name }}/.oh-my-zsh'
    accept_hostkey: yes

- name: Install tmux plugin manager
  become: yes
  become_user: '{{ user_name }}'
  git:
    repo: https://github.com/tmux-plugins/tpm
    version: master
    dest: '/home/{{ user_name }}/.tmux/plugins/tpm'
    accept_hostkey: yes

- name: Install vundle plugin manager
  become: yes
  become_user: '{{ user_name }}'
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    version: master
    dest: '/home/{{ user_name }}/.vim/bundle/vundle'
    accept_hostkey: yes

- name: Install emacs configuration
  become: yes
  become_user: '{{ user_name }}'
  git:
    repo: https://github.com/danielfm/dotfiles-emacs.git
    version: master
    dest: '/home/{{ user_name }}/.emacs.d'
    accept_hostkey: yes

- name: Get vscode
  become: yes
  get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: "/home/{{ user_name }}/Downloads/playbook/vscode.deb"

- name: Install vscode
  become: yes
  apt:
    deb: "/home/{{ user_name }}/Downloads/playbook/vscode.deb"
